# 配置项目信息
application:
  version: 2.0.0

server:
  port: 10086

spring:
  application:
    name: skc-practice
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

